### ISSUE TITLE
Sorting by name acts weird with GregTech

### ISSUE THREAD

**Issue by MauveCloud** [TinyModularThings/IC2-Nei-Plugin#4]
With GregTech 5.09 installed, when I tell the Crop Breeding Calculator to sort by name, all the IC2 crops come between God of Thunder and Indigo.

**Comment by Speiger** [comment]
@MauveCloud Yes simply because thats how the CropAPI is handling that.
Just to throw that out. IC2 API has a function called displayName.
IC2 Classic returns as display name the Localized name.
IC2 Exp returns the Uncalized name.
That is not a bug of IC2 Nei Plugin.
Its actually a bug of IC2 Exp, simply because their API is to confusing. They want to have at displayName a UnlocalizedName (which makes no sence) but everyone except IC2 Exp (even GT (Did ask greg before that)) returns the DisplayNames there...
I can not make a fix there because IC2 Exp is the problem.... And i do not think that they will fix it...
(I really can not fix it because i would have to detect some how which crop is now returning the wrong name and which is returning the Right Name)

**Comment by MauveCloud** [comment]
Don't the ic2 unlocalized names for crop seeds all start with the same prefix, like "ic2.crop" or something?  Seems like you'd be able to work from that.  Also, at least with the icons enabled, they show as "Crop Galvania", "Crop Aurelia", etc.  Isn't it possible to sort based on those display names instead?

**Comment by Speiger** [comment]
@MauveCloud yeah its partly right... But what if IC2 crops do not start anymore with the prefix?
I mean i can understand that. But they should fix their api in the first place...
I do not really call that a high priority system. Which by the way need a IC2 Classic Detection too...
